var STORIES =
[
  {
    "text": "FIVwzgLgBA5g9lAZnATlAltAhgOwCazoBuAphtlBCgJ4CEUAmnCFHnDgOTQAWWplCAEZksUAA4o4iEmDDp2WADYCogkOkUFRYEAGNdMsIhDKJcPHogA6KAEEAtlggkQKMFEhYUzggHE4cDCKIvh2YmLBNgAKktKy8jhK7moa0BDcZAAqmLjoukA=",
    "length": 167
  },
  {
    "text": "CoewJghgngNABBALnAtlVJEAsCmAnAcgGc4AzAVwDt8IAbeXPOAIxyOVLwEsdKw4QpOABYADHCg4IeEgGMIKHHHIAHOIhColEPgiIBrHP0VwsIAO5wAknH3VL2JWByypRI0A",
    "length": 109
  },
  {
    "text": "CoJwhgbgpgNglgOwOYAJEoNJQQTzAGhQEkUBbKAFxTBRCgDMBXJKKFekAe1JQC05SAIzCCA7lAB0KABJsAzmDgATFAAs2qsEoQByKlDAVs1XBVWJU6TtBAoAzCiVgcckypidOAaygqoADwo6chgcFDkvRFw3FEYEdTAYMxwpEjowAGN1FXRSMOFUMAQVTnp6KDoVcx488KKlUTgsqWB1djgQOSozCzV5RRVRMDlCACIAdTYMovDNOjQKCVGgA===",
    "length": 238
  },
  {
    "text": "LITwBA5gTghgdgEwLYzAZwC4EsA2OwDuApjFGmBgBZFgBGJCRCdsAxkTkRmEuNPAgAOqFIzAAzAPZQw1GQWpwK1cMSg0sSylgiV0rSpMk4gA",
    "length": 96
  },
  {
    "text": "CoewJghgngBAkjA7hAzjCAHDAnEEDGAFgKZgwBGsEMhIAtsQDbEpp0QB2St6KA1qRgBLAGbwaEMp1hFOAc2IA6cSA6NYhSTAAuiEDDBCGKADQUArtvFyIAN2LCr2/YSPoOUZFGUBBNAmRtIkFXOiQIRj50LzMSGAxLHTjDY2EuThhiAA8MIWxBDAhsPiEOORgGbWJsGBAxahRtbHlqtHwioA",
    "length": 214
  },
  {
    "text": "LITwBAJghgrg5gCwC4FMBOYDuCD2YDOSa8cANihGEnnCkmAMIDk+YAlgHZhxpQQoEAxrhykwOTB1ZQwAWxikkbALSy2pUmxxcIo0lAyCc+WXTaDWR2QAcoHEADowoSLESoM2PJiitOVBAE4NgAzVEprNBweKFl2Lhj+IRExNlYEKGtrdXAUG1IcEAowXxKwAGtOfjQ4A1QuVChhdDkoSo44MAASAGYAVgBpMqKDJ2A2lFYQHBgAznKgA",
    "length": 239
  },
  {
    "text": "IIAgNglgLlYKYgEbRAewGYgNYDtUHd4ATAcwQEMciRzxUo1NyBjKCVHGsfcgTwGcQUAE4BXALYAHQbTD1G2PITikKVEHhqt2OIA=",
    "length": 92
  },
  {
    "text": "CoCwhgLg5AzgBBEBTBICWA7A5nMAjAewFcI4AHJAsgGxQHcQDVMBrVJATznAhQGMCAWzIkkAJxgA6OAHUe7LmKRhq1LjxRp41YjC5kxBLGLCDB4mEA==",
    "length": 103
  },
  {
    "text": "BIew7gBAniCuEBsQgNYQIYBcIEts4GcIAHAJwFNNMoIBbWAYwAsInxo4ByBBCA88rkxA",
    "length": 51
  },
  {
    "text": "CoCwpgBALiCWB2BzAztEBDKEC26DWkArqhgA6kCeANDvkagO6zJhA===",
    "length": 43
  },
  {
    "text": "CoCwpgBAwiCWB2YDOYA0ECeB7ArhA1vFgO7oBGYANrGAG6QAuIAhgxACZhgAOExsTBBDDMAxiAhYAZhBxJ0RCJWYAnAOZgVEJs3jbwEMs0qVJM7Di1McAWzLpYSfZDWrOe6c4iwbNrCoZjeS81FRE2WmNKMAw+cDC+SFUkkwIENQgpfzpNIA",
    "length": 177
  },
  {
    "text": "JIFwBAlgzmB2D256wDYE8wgBYFMwDcJ4UJZMsBDcKSgBxxmz0ONOhABowB3PCgJz4oUYGhXoATMACMMTTPGIxemfhVJh4AV35QcKfAwVgterhVhSN2aGEFR6AY3C1+8AOZqAtl9LuwKBbuWhTuRpSGYBRgEjgsppCwAGYoWjiwjjgAXOQ4GGL0mjrkpADWfkA===",
    "length": 202
  },
  {
    "text": "DISwZgpgBAJg9hAzgOwOQBcoAsCGA3aHKAYQBUAlYAWgC0A6KUgTwAdoB3ERCAGyaA==",
    "length": 39
  },
  {
    "text": "JoewrgTgBANglgWzgFwIbLiAdgZyqiAU1gIHNCYBPKABwhFIlQSS1KjlwxhkIBMoAI2ohkAC0IQ849FErgoAYzEgQOYshBCKcQgDdCQA",
    "length": 87
  },
  {
    "text": "MoewtgpgLglpDOACGVEAcCGBPJUSPim2QDtEAjCAE0RDIFk6rsAaRAJwygAsJ3EeGMvDQQSVGCQDmA3hwiFaAM1kREAdwgQA1oiUwAHpJk81adiHIAbCGCRYQAV0QBjdhC7VaDJtiA==",
    "length": 127
  },
  {
    "text": "JoewrgBCB2A2CeFYEsBuBTK0DG6A0EARmAC4TIBmE84EAJiOWQE7IDmAFiQTLuQM4R00cJyA",
    "length": 58
  },
  {
    "text": "DISwZgpgBCDOB2ByALlAhgIwPYFdVhHgBNCBzKAT1wCdYIAbMAOilEhlnWzygGNqIaZGUo06jIA=",
    "length": 66
  },
  {
    "text": "DISwZgpgBCDOUBsQGtoCcQBMQDsDmUAhlAEYgDGAnuQhAHRQAqA9lKhAA5SXMCuapQgkI5yEADTc+UALa9YAFzYROs5gDdceIA==",
    "length": 73
  },
  {
    "text": "EQQQZgLgpgTgBAQwDZLhAFgSwM5swWygH5g5QkB3BAT2wBpTsFMATOAZQDsEAHKIA===",
    "length": 43
  },
  {
    "text": "CoUwNmAEC2IDSQO4AsCGAXSBLAztzAngPYCukADmKgHaTpGQAmDiW6ykxJATpEdSCRYwjSDVHluIAMZZSeMFgBmIAPxA",
    "length": 72
  },
  {
    "text": "CoCwpgBAzmDGBOYAuED2AzaBXWsxSgBoIkRUsBzEYgSyhNQnQEMAbV6MANzADsSaAW3wRmvACYMIFZBCwAHCGBpUUSIfiA==",
    "length": 79
  },
  {
    "text": "JIcgtgBAhhDOCuBjRBTWsIBcD2ATKAnhAEYqJTywoTAQAWUu0EAZgE4CWKAdkwO51sJFABsuANxRMO3CGGpReNCLg65uITPSiSsdavqhstOCCJRa6HSLmx9uQA==",
    "length": 105
  },
  {
    "text": "IIOwngRg9gJmAEBjAhieBnMBbADsgLgBYCW6ApvAO7FHxEXoCuAZs2QE7EgDm68UzeMnjNOZEDAA08CI3zwa8dmQCOjYsr7CAbhwTMuFEAUbK6UDNjxFSFarWGji4mAHI+TRIjLp0QA=",
    "length": 128
  },
  {
    "text": "LIexDsBsEsHMAsAuACAZpMATAzsx8BTZAd3hEiOwGsBPNAJxAFtkz7oAvCPEVkdruADcyABIhiyJgFcAxvGTQUsgIbg00SJGQ0Q0+skbNkmAgAcC4HMm679JaFYnYgA=",
    "length": 110
  },
  {
    "text": "OoCwpgdgBAzg9gWzHCYoEsZRAQwgE3QgHNZEwAXEI0uAVwqgDM4AnKAT3oBop8UA5IwA2cOAGsoORlzrtcBGLzZQA7rkbpNMAHRQAMmMnSoVNMXQA3MKyA==",
    "length": 105
  },
  {
    "text": "JIFw5AzgBAdg9iKBDRSA2aoEsC2AHOAJxCRkRDigHMBTRLRQrKgC3JZqgDMtCJzcNAHRRQkKIRro0AT2z4iJMlArU62RszYqOUNEn4rBQA==",
    "length": 109
  },
  {
    "text": "OIewBARghgxg1gfjAOXAcxCAJmKAXXAG0IEIxQwBnASywFMB3KAT0qQEkBbABxEpoiE6ZCgDMQAJyYSsSAPIA7QszB4AFtQVpV4LCDKKwDOmAwkgA===",
    "length": 89
  },
  {
    "text": "GIJw9gtgBALgFgUyhSCB2MoEkoAcCWAxgNYIAmUAnmAK4hQBGYYxUNubG+ANtlNwEN8FfJjJgA7mj4SBAZyiEwaAG41uc8lAmi4/ATQDmcGAhAA6KAGVUUMgMp98GdBRAIBZZ4aiigA=",
    "length": 118
  },
  {
    "text": "EISw5ghgtgngBCAznAFhAbiAdmOB7LAUzgHcQAzYgFzzzigixgDo4BZAvSWBZKlYomiEgA==",
    "length": 56
  },
  {
    "text": "IIGxAIE8HsFdwHYFMkBNwEsDO4vQLZIAuAFhggObhHTiq2kCGR4+0AbkjjLADTiNWSRgnIUAZrAj4MILjWTVajLAAcMAJyRL+I9HkLRFapAGMMjCDVwlGWqHA3gAVo+SRwAdwykgA===",
    "length": 131
  },
  {
    "text": "CoewJghgngNABASThAxiglmApgOwC4QA2hUcAzrnsnHlgB5UC2WZZEA5lnOvrtmHABmIAE5xGpABYBXMgCMIOAXhDjSgiHklYRAWh67CEAO4A6OABlpKANboS3KiBwO2mOACIkhEADcuUCDSph5wALLqmtp6BkbG5JTiXBBwIlhErsZYWFRpAA4OigJk6Ow4WALoVB4WfljwACIQYKHCYlpcgugiZFR46MxAA===",
    "length": 212
  },
  {
    "text": "CIVwpgBALg9hCCAbAXgCzASwLZgE4HIBnCAQwDsATCCsHMqDEgGgiwE8IBzXcigMxJR0uCCEIgSiRBwDG5fFAi5atAEZ4IAd1Rx2XHpSwwhGjMW1gyEdFpIBrMMRAAHCBisnWMXGXecAdBAAkoqqxsJgVHrcvEYmIiQQbGAkCZxwFlYYinwYuISKqCTOzpaRLKogimQwmhCE6EQQfCBSHOIl3gwAbpAwfNZmEDIwlNkYo4FBVgIyUCwNkM6IJGzEiZwkOBBgvbgcFKtuVtoYMqj1NlC4GI7QcJxgitEG/ILC96SEdtYasEpgAC0WFS+0GWAg6j43kgFHcZDwDBwgQAyjYioQyApmiQMIhIkknkA=",
    "length": 381
  },
  {
    "text": "CoewJghgngNABASTgWwKYBc7oBargBwCcN0BLVAZ0wHcRkIA7OEJxuCUw/AG0dQDo4AQQBm6VITgU6eCvW7csEbgGt4jMHACuDMBKy52FCluT4yLAxExJaW7mAYByTBVR5ckiAHMOrMfrUePR6zFqSAMYsDKgRFgwUcKRMQui8DOgQ8EjoIA5wngUg1ATE6OhQiAYgWt7YrobUEBSCAMqGvgBuwXg4wSBUUskRErLIpNx4GlIcYPAARAByIABG4JXYzTOkmjjWWCAoeMlwAIwADHBQqBCELfOImOjhCWE0qICYBMRwazhJTDVJOMwABaADM5ycFHgMW6QNuhHIczgDEOKh20PYujgQTg3FI3XYay0mAArCgJpR2E1KiJCHQ4DcIthmH1JCcACLKXgtOAAdQ8EEJEDgkHEUgwcBEIEkMQAHphWtZwpBKhAApJcWUXkU0EA===",
    "length": 477
  },
  {
    "text": "CoewJghgngNABBOALEBbApgG3QZx3VCAOzgHcVU4BJOAJ3QGMQBzIgSwC904AzWtBPwCuRMHAAuSbkXRtmSAEYhaKcHAYQMcNkXEgCUOAogBrdLUPExAByG0GSCDnRjEmCLWbcFbWpMiGGmZwABQ0zBAAbtxIbJSIACwADACkcGBsOEwi4gCUAHTU6nZsIEI4mIakEOIOLgj4UmQQmGZiktxB3BAM/HgSTTji9OjiEvrEIB20yGhYuPiERIXATVNSM0twQx7i9e5C8jrMCKID6CQdEqT6GCRIh15gQA=",
    "length": 296
  },
  {
    "text": "LITwBARg9iBmBOBLApgOwCZgIYbASTAHc0AXMEqcgC2TAGMoBXVE8WLReAGjHinVokaYAGLJ4SAM5EayADY8sJWnRzpwDeKkW4haMMMJRUYALa0sYSSUaxYyTMvTrylOvOQR4S2qfAB2AE4hSE4hdCwQIA==",
    "length": 147
  },
  {
    "text": "CoewJghgngNABASwHZwC4AsCmcDmAnEAY0zyjgGdUQ9sAHCPAa2RzgBsRV4BJOAdwipCWMHAhwAthBR4Arigjk4AM0WoxSrHEIhZbUXwQYxceoUaZR5dCFq0W2huumiMmFACtZE2nBAo3OAAjCHMVahM8BDBMADo4AAlscgkENksxJFFhWXN00QgOWQLNbAIYtC1CJzE2NkrsATIqOHQEJWq8eKT+RUQUNqVUsABaABYABgByJRd+TAYHcWVqKXryWSNM1wRMIA=",
    "length": 276
  }
]
